apiVersion: v1
kind: Service
metadata:
    name: database02
    namespace: boxlinker
    labels:
        name: database02
spec:
    selector:
        name: database02
    ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
    - name: galera
      port: 4567
      targetPort: 4567
