apiVersion: v1
kind: List
items:
# ucenter config

- apiVersion: v1
  kind: Service
  metadata:
    name: imageauth
    namespace: boxlinker
    labels:
      name: imageauth
    annotations:
      serviceloadbalancer/lb.http: imageauth.boxlinker.com:8001
      serviceloadbalancer/lb.node: main
  spec:
    ports:
    - port: 8001
      targetPort: 8843

- apiVersion: v1
  kind: Endpoints
  metadata:
    name: imageauth
    namespace: boxlinker
  subsets:
    - addresses:
      - ip: 192.168.1.6
      ports:
        - port: 8843




