apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-api
  namespace: boxlinker
  labels:
    component: k8s-api
    rc-krud: boxlinker_centos-k8sapi
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-api
      namespace: boxlinker
      labels:
        logs: boxlinker-k8s-api
        name: k8s-api
        component: k8s-api
    spec:
      nodeSelector:
        role: system
      containers:
      - name: k8s-api
        image: index.boxlinker.com/boxlinker/centos-k8sapi:1.2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api
  namespace: boxlinker
  annotations:
    serviceloadbalancer/lb.http: api.boxlinker.com:9000
    serviceloadbalancer/lb.node: main
    serviceloadbalabcer/lb.sslTerm: "true"
spec:
  selector:
    component: k8s-api
  ports:
  - port: 9000