FROM nginx
MAINTAINER xiaofengwang
COPY ./auth /usr/share/nginx/html/
COPY ./k8s /usr/share/nginx/html/
COPY ./storage /usr/share/nginx/html/
COPY ./monitor /usr/share/nginx/html/
COPY ./billing /usr/share/nginx/html/
COPY ./index.html /usr/share/nginx/html/
COPY ./log /usr/share/nginx/html/
COPY ./usercenter /usr/share/nginx/html/
COPY ./apprecover /usr/share/nginx/html/
COPY ./imageauth /usr/share/nginx/html/
COPY ./security /usr/share/nginx/html/

