apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: docs
    namespace: boxlinker
    labels:
      component: docs
    annotations:
      serviceloadbalancer/lb.http: "docs.boxlinker.com:80"
      serviceloadbalancer/lb.node: "main"
  spec:
    selector:
      component: docs
    ports:
    - port: 3000
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: docs
    namespace: boxlinker
    labels:
      component: docs
      rc-krud: "boxlinker_docs"
  spec:
    replicas: 1
    selector:
      component: docs
    template:
      metadata:
        name: docs
        labels:
          component: docs
      spec:
        nodeSelector:
          role: node
        imagePullSecrets:
        - name: RegistryWeb-key
        containers:
        - name: fe
          image: index.boxlinker.com/boxlinker/docs:1.0
          imagePullPolicy: Always
          env:
          ports:
          - containerPort: 80
            name: pro